apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sam
spec:
  selector:
    matchLabels:
      app: my-sam
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: my-sam
    spec:
      containers:
        - name: my-sam
          image: formycore/ci
          imagePullPolicy: Always
          ports:
            - containerPort: 80